"key = USB_VID val = f055\r\n"
"key = USB_PID_CDC_MSC val = 9800\r\n"
"key = USB_PID_CDC_HID val = 9801\r\n"
"key = USB_PID_CDC val = 9802\r\n"
"key = USB_PID_MSC val = 9803\r\n"
"key = USB_PID_CDC2_MSC val = 9804\r\n"
"key = USB_PID_CDC2 val = 9805\r\n"
"key = USB_PID_CDC3 val = 9806\r\n"
"key = USB_PID_CDC3_MSC val = 9807\r\n"
"key = USB_PID_CDC_MSC_HID val = 9808\r\n"
"key = USB_PID_CDC2_MSC_HID val = 9809\r\n"
"key = USB_PID_CDC3_MSC_HID val = 980a\r\n"
"; Windows USB CDC ACM Setup File\r\n"
"; Based on INF files which were:\r\n"
";     Copyright (c) 2000 Microsoft Corporation\r\n"
";     Copyright (C) 2007 Microchip Technology Inc.\r\n"
"; Likely to be covered by the MLPL as found at:\r\n"
";    <http://msdn.microsoft.com/en-us/cc300389.aspx#MLPL>.\r\n"
"\r\n"
"[Version]\r\n"
"Signature=\"$Windows NT$\"\r\n"
"Class=Ports\r\n"
"ClassGuid={4D36E978-E325-11CE-BFC1-08002BE10318}\r\n"
"Provider=%MFGNAME%\r\n"
"LayoutFile=layout.inf\r\n"
"DriverVer=03/11/2010,5.1.2600.3\r\n"
"\r\n"
"[Manufacturer]\r\n"
"%MFGNAME%=DeviceList, NTamd64\r\n"
"\r\n"
"[DestinationDirs]\r\n"
"DefaultDestDir=12\r\n"
"\r\n"
";---------------------------------------------------------------------\r\n"
"; Windows 2000/XP/Server2003/Vista/Server2008/7 - 32bit Sections\r\n"
"\r\n"
"[DriverInstall.nt]\r\n"
"include=mdmcpq.inf\r\n"
"CopyFiles=DriverCopyFiles.nt\r\n"
"AddReg=DriverInstall.nt.AddReg\r\n"
"\r\n"
"[DriverCopyFiles.nt]\r\n"
"usbser.sys,,,0x20\r\n"
"\r\n"
"[DriverInstall.nt.AddReg]\r\n"
"HKR,,DevLoader,,*ntkern\r\n"
"HKR,,NTMPDriver,,usbser.sys\r\n"
"HKR,,EnumPropPages32,,\"MsPorts.dll,SerialPortPropPageProvider\"\r\n"
"\r\n"
"[DriverInstall.nt.Services]\r\n"
"AddService=usbser, 0x00000002, DriverService.nt\r\n"
"\r\n"
"[DriverService.nt]\r\n"
"DisplayName=%SERVICE%\r\n"
"ServiceType=1\r\n"
"StartType=3\r\n"
"ErrorControl=1\r\n"
"ServiceBinary=%12%\\usbser.sys\r\n"
"\r\n"
";---------------------------------------------------------------------\r\n"
";  Windows XP/Server2003/Vista/Server2008/7 - 64bit Sections\r\n"
"\r\n"
"[DriverInstall.NTamd64]\r\n"
"include=mdmcpq.inf\r\n"
"CopyFiles=DriverCopyFiles.NTamd64\r\n"
"AddReg=DriverInstall.NTamd64.AddReg\r\n"
"\r\n"
"[DriverCopyFiles.NTamd64]\r\n"
"usbser.sys,,,0x20\r\n"
"\r\n"
"[DriverInstall.NTamd64.AddReg]\r\n"
"HKR,,DevLoader,,*ntkern\r\n"
"HKR,,NTMPDriver,,usbser.sys\r\n"
"HKR,,EnumPropPages32,,\"MsPorts.dll,SerialPortPropPageProvider\"\r\n"
"\r\n"
"[DriverInstall.NTamd64.Services]\r\n"
"AddService=usbser, 0x00000002, DriverService.NTamd64\r\n"
"\r\n"
"[DriverService.NTamd64]\r\n"
"DisplayName=%SERVICE%\r\n"
"ServiceType=1\r\n"
"StartType=3\r\n"
"ErrorControl=1\r\n"
"ServiceBinary=%12%\\usbser.sys\r\n"
"\r\n"
";---------------------------------------------------------------------\r\n"
";  Vendor and Product ID Definitions\r\n"
"\r\n"
"[SourceDisksFiles]\r\n"
"[SourceDisksNames]\r\n"
"[DeviceList]\r\n"
"%DESCRIPTION%=DriverInstall, USB\\VID_f055&PID_9800&MI_00, USB\\VID_f055&PID_9800&MI_01, USB\\VID_f055&PID_9801&MI_00, USB\\VID_f055&PID_9801&MI_01, USB\\VID_f055&PID_9802\r\n"
"\r\n"
"[DeviceList.NTamd64]\r\n"
"%DESCRIPTION%=DriverInstall, USB\\VID_f055&PID_9800&MI_00, USB\\VID_f055&PID_9800&MI_01, USB\\VID_f055&PID_9801&MI_00, USB\\VID_f055&PID_9801&MI_01, USB\\VID_f055&PID_9802\r\n"
"\r\n"
";---------------------------------------------------------------------\r\n"
";  String Definitions\r\n"
"\r\n"
"[Strings]\r\n"
"MFGFILENAME=\"pybcdc\"\r\n"
"MFGNAME=\"MicroPython\"\r\n"
"DESCRIPTION=\"Pyboard USB Comm Port\"\r\n"
"SERVICE=\"USB Serial Driver\"\r\n"
